import { type ReactNode, useEffect, useState } from 'react';
import { QueryClient, QueryClientProvider, useQueryClient } from '@tanstack/react-query';
import { ErrorBoundary } from '@/components/error-boundary';
import { Toaster } from '@/components/ui/toaster';
import { TooltipProvider } from '@/components/ui/tooltip';
import NotFound from '@/pages/not-found';
import { Link, Route, Switch, useLocation, Router as WouterRouter, useRoute } from 'wouter';
import { ArrowDownRight, ArrowRight, Check, CheckCircle2, Clipboard, Clock3, ExternalLink, Heart, IndianRupee, Leaf, LoaderCircle, LockKeyhole, LogOut, Mail, Plus, Sparkles, Sprout, Trash2 } from 'lucide-react';
import { getGetCurrentTherapistQueryKey, getGetPublicTherapistProfileQueryKey, getHealthCheckQueryKey, useGetCurrentTherapist, useGetPublicTherapistProfile, useHealthCheck, useLoginTherapist, useLogoutTherapist, useRegisterTherapist, useUpdateTherapistProfile } from '@workspace/api-client-react';
import type { Therapist, TherapistProfileUpdate, TherapistServiceInput } from '@workspace/api-client-react';

const queryClient = new QueryClient({ defaultOptions: { queries: { retry: 1, refetchOnWindowFocus: false } } });
const errorMessage = (error: unknown, fallback: string) => {
  if (error && typeof error === 'object' && 'error' in error && typeof error.error === 'string') return error.error;
  if (error instanceof Error) return error.message;
  return fallback;
};
const initials = (name: string) => name.split(/\s+/).filter(Boolean).slice(0, 2).map((part) => part[0]).join('').toUpperCase();
const makeSlug = (name: string) => name.toLowerCase().trim().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '').slice(0, 48);
const splitTags = (value: string) => value.split(',').map((item) => item.trim()).filter(Boolean);
type ServiceDraft = { title: string; description: string; durationMinutes: string; feeInr: string };
const blankService = (): ServiceDraft => ({ title: '', description: '', durationMinutes: '', feeInr: '' });
const formatINR = (amount: number) => new Intl.NumberFormat('en-IN', { style: 'currency', currency: 'INR', maximumFractionDigits: 2 }).format(amount);

function Brand({ light = false }: { light?: boolean }) {
  return <Link href="/" className={`inline-flex items-center gap-2.5 ${light ? 'text-[#f7f3e9]' : 'text-[#294f43]'}`} data-testid="link-brand-home"><span className="flex h-9 w-9 items-center justify-center rounded-full bg-[#e1e9da]"><Sprout size={19} strokeWidth={1.8} /></span><span className="text-[21px] font-semibold tracking-[-.05em]">unfazed<span className="text-[#d38e73]">.</span></span></Link>;
}
function Header({ dashboard = false, onSignOut, signingOut = false }: { dashboard?: boolean; onSignOut?: () => void; signingOut?: boolean }) {
  return <header className="flex items-center justify-between border-b border-[#dfd9ca] px-5 py-4 md:px-10"><Brand /><div className="flex items-center gap-3">{dashboard ? <><Link href="/" className="text-sm text-[#68766d] hover:text-[#294f43]" data-testid="link-home">Home</Link>{onSignOut && <button type="button" onClick={onSignOut} disabled={signingOut} className="btn btn-ghost !px-4 !py-2 text-sm" data-testid="button-sign-out">{signingOut ? <LoaderCircle className="animate-spin" size={15} /> : <LogOut size={15} />}{signingOut ? 'Signing out…' : 'Sign out'}</button>}</> : <><span className="hidden text-sm text-[#718078] sm:inline">A softer way to begin</span><Link href="/login" className="btn btn-ghost !px-4 !py-2 text-sm" data-testid="link-login">Log in</Link></>}</div></header>;
}
function HealthPill() {
  const { data, isLoading, isError } = useHealthCheck({ query: { queryKey: getHealthCheckQueryKey(), staleTime: 30000 } });
  return <div className="inline-flex items-center gap-2 rounded-full border border-[#d9dfcf] bg-[#f8f7ef] px-3 py-1.5 text-xs text-[#627368]" data-testid="status-api-health"><span className={`h-1.5 w-1.5 rounded-full ${isLoading ? 'bg-[#c9a77d]' : isError ? 'bg-[#bd665a]' : 'bg-[#709b7c]'}`} />{isLoading ? 'Checking availability' : isError ? 'Service reconnecting' : data?.status === 'ok' ? 'A steady place to start' : 'Here when you are ready'}</div>;
}
function Home() {
  return <main className="min-h-[100dvh] overflow-hidden bg-[#f3f0e7]">
    <Header />
    <section className="page-wrap relative grid min-h-[625px] items-center gap-10 py-16 md:grid-cols-[1.08fr_.92fr] md:py-20">
      <div className="absolute -left-32 top-16 h-80 w-80 rounded-full bg-[#e6e9da] blur-3xl opacity-70" />
      <div className="relative animate-rise"><HealthPill /><p className="eyebrow mt-8">For therapists, in private practice</p><h1 className="serif mt-4 max-w-[680px] text-[clamp(3.8rem,7.2vw,6.5rem)] leading-[.9] tracking-[-.035em] text-[#284d41]">Make room for<br /><em className="text-[#bc8068]">a first hello.</em></h1><p className="mt-7 max-w-[490px] text-lg leading-8 text-[#67746b]">A calm, considered home for your practice — and a warm first step for the people looking for support.</p><div className="mt-9 flex flex-wrap items-center gap-3"><Link href="/register" className="btn btn-primary" data-testid="link-create-profile">Create your profile <ArrowRight size={17} /></Link><Link href="/login" className="px-3 py-3 text-sm font-semibold text-[#456354] hover:underline" data-testid="link-returning-therapist">I already have an account</Link></div><div className="mt-11 flex items-center gap-3 text-sm text-[#718078]"><span className="flex -space-x-2"><i className="flex h-8 w-8 items-center justify-center rounded-full border-2 border-[#f3f0e7] bg-[#d9b8a5] text-[10px] not-italic text-[#624c3e]">A</i><i className="flex h-8 w-8 items-center justify-center rounded-full border-2 border-[#f3f0e7] bg-[#b8c7ae] text-[10px] not-italic text-[#355044]">R</i><i className="flex h-8 w-8 items-center justify-center rounded-full border-2 border-[#f3f0e7] bg-[#e8d8b9] text-[10px] not-italic text-[#625540]">M</i></span><span>Built around the way care actually begins</span></div></div>
      <div className="relative mx-auto w-full max-w-[445px] animate-rise [animation-delay:120ms]"><div className="absolute -right-4 -top-5 z-10 flex h-16 w-16 rotate-6 items-center justify-center rounded-full bg-[#d7e1d0] text-[#41644f] shadow-md"><Heart size={26} strokeWidth={1.5} /></div><div className="relative overflow-hidden rounded-[42%_42%_26px_26px] bg-[#d9e1d2] px-8 pt-10 shadow-[0_28px_70px_rgba(42,69,53,.13)]"><div className="absolute inset-x-0 top-0 h-44 bg-[#e8e5d8]" /><div className="relative mx-auto flex h-[390px] max-w-[330px] flex-col items-center justify-end overflow-hidden rounded-t-[46%] bg-[#a9b99f]"><div className="absolute inset-0 opacity-70" style={{backgroundImage:'radial-gradient(ellipse at 50% 10%, #d2d7c2 0%, transparent 45%),linear-gradient(130deg,transparent 40%,#8fa58e 40%,#8fa58e 61%,transparent 61%)'}} /><div className="relative mb-0 flex h-[248px] w-[214px] items-start justify-center rounded-t-[48%] bg-[#e2bba1]"><div className="mt-16 h-16 w-20 rounded-[45%] bg-[#593f35]" /><div className="absolute bottom-0 h-[112px] w-[230px] rounded-t-[48%] bg-[#f4efe4]" /><div className="absolute bottom-[104px] h-[52px] w-[70px] rounded-b-[50%] bg-[#d6a489]" /></div><div className="absolute left-5 top-14 h-32 w-10 rotate-12 rounded-full bg-[#718a71]/50" /><div className="absolute right-7 top-20 h-24 w-8 -rotate-12 rounded-full bg-[#718a71]/50" /></div><div className="absolute bottom-5 left-6 rounded-xl border border-white/60 bg-[#f8f5ed]/95 px-4 py-3 shadow-lg backdrop-blur"><p className="eyebrow !text-[9px]">A place to begin</p><p className="serif mt-0.5 text-xl text-[#315447]">One step, at your pace.</p></div></div><div className="absolute -bottom-5 -left-7 -z-0 h-28 w-28 rounded-full border border-[#c8d0bf]" /></div>
    </section>
    <section className="border-y border-[#e0dbce] bg-[#eeece2] py-14"><div className="page-wrap grid gap-8 md:grid-cols-[.7fr_1.3fr] md:items-center"><div><p className="eyebrow">A beginning that feels like you</p><h2 className="serif mt-3 text-4xl text-[#294f43]">Care starts before<br />the first session.</h2></div><p className="max-w-[640px] text-[16px] leading-8 text-[#68756c]">Finding a therapist can take courage. Your profile gives someone the chance to understand how you work, what you can support them with, and whether this feels like a safe place to start.</p></div></section>
    <section className="page-wrap grid gap-12 py-20 md:grid-cols-[.8fr_1.2fr] md:py-24"><div><p className="eyebrow">Simple by design</p><h2 className="serif mt-4 text-5xl leading-[.98] text-[#294f43]">Your practice,<br /><em>beautifully introduced.</em></h2><Link href="/register" className="mt-7 inline-flex items-center gap-2 text-sm font-semibold text-[#426551]" data-testid="link-get-started">Set up your profile <ArrowDownRight size={16} /></Link></div><div className="grid gap-4 sm:grid-cols-2"><article className="rounded-3xl bg-[#e6eadd] p-7"><span className="flex h-10 w-10 items-center justify-center rounded-full bg-[#d1ddc9] text-[#426551]"><Leaf size={20} /></span><h3 className="serif mt-6 text-2xl text-[#315447]">A profile with presence</h3><p className="mt-2 text-sm leading-6 text-[#68766c]">Share your approach, areas of focus and the languages you work in.</p></article><article className="mt-6 rounded-3xl bg-[#f0e5d8] p-7 sm:mt-14"><span className="flex h-10 w-10 items-center justify-center rounded-full bg-[#e6d1bd] text-[#925f4a]"><Sparkles size={19} /></span><h3 className="serif mt-6 text-2xl text-[#684d3f]">A link that is yours</h3><p className="mt-2 text-sm leading-6 text-[#786b60]">One simple, memorable address to share wherever people find you.</p></article></div></section>
    <footer className="border-t border-[#ded9cb] py-8"><div className="page-wrap flex flex-wrap items-center justify-between gap-4"><Brand /><p className="text-xs text-[#7a8178]">A thoughtful first step toward feeling better.</p></div></footer>
  </main>;
}

function AuthPage({ mode }: { mode: 'register' | 'login' }) {
  const isRegister = mode === 'register';
  const [, setLocation] = useLocation();
  const queryClient = useQueryClient();
  const register = useRegisterTherapist();
  const login = useLoginTherapist();
  const pending = register.isPending || login.isPending;
  const [name, setName] = useState(''); const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [problem, setProblem] = useState('');
  const submit = (event: React.FormEvent<HTMLFormElement>) => {
    event.preventDefault(); setProblem('');
    const onSuccess = (session: { therapist: Therapist }) => { queryClient.setQueryData(getGetCurrentTherapistQueryKey(), session.therapist); void queryClient.invalidateQueries({ queryKey: getGetCurrentTherapistQueryKey() }); setLocation('/dashboard'); };
    const onError = (error: unknown) => setProblem(errorMessage(error, 'We could not complete that just now. Please try again.'));
    if (isRegister) register.mutate({ data: { name: name.trim(), email: email.trim(), password } }, { onSuccess, onError });
    else login.mutate({ data: { email: email.trim(), password } }, { onSuccess, onError });
  };
  return <main className="grid min-h-[100dvh] bg-[#f3f0e7] md:grid-cols-[.92fr_1.08fr]"><section className="relative hidden min-h-[100dvh] overflow-hidden bg-[#365a4c] px-12 py-10 text-[#f5f1e7] md:flex md:flex-col"><div className="absolute -right-28 top-24 h-[430px] w-[430px] rounded-full border border-white/10" /><div className="absolute -right-12 top-40 h-[300px] w-[300px] rounded-full border border-white/10" /><Brand light /><div className="relative my-auto max-w-[420px] pb-20"><p className="eyebrow !text-[#c7d4b8]">A little less alone</p><h1 className="serif mt-5 text-6xl leading-[.95]">A good first step<br />can change <em>things.</em></h1><p className="mt-6 max-w-[330px] leading-7 text-[#d5ddd3]">Make it easier for the right people to find their way to your practice.</p><div className="mt-12 flex items-center gap-3 border-t border-white/15 pt-5 text-sm text-[#d5ddd3]"><span className="flex h-9 w-9 items-center justify-center rounded-full bg-white/10"><Heart size={17} /></span>Made for the work you do.</div></div><div className="relative flex items-center gap-2 text-xs text-[#b9c9bc]"><LockKeyhole size={14} />Your account stays yours. Always.</div></section><section className="flex min-h-[100dvh] flex-col px-5 py-6 sm:px-10 md:px-14"><div className="md:hidden"><Header /></div><div className="mx-auto my-auto w-full max-w-[430px] py-10 animate-rise"><div className="mb-8 hidden md:block"><Link href="/" className="text-sm text-[#78847a]" data-testid="link-back-home">← Back to home</Link></div><p className="eyebrow">{isRegister ? 'Start with your practice' : 'Welcome back'}</p><h2 className="serif mt-3 text-5xl leading-none text-[#294f43]">{isRegister ? 'Create your account.' : 'Good to see you.'}</h2><p className="mt-4 text-sm leading-6 text-[#728076]">{isRegister ? 'A few details, then we’ll help you make a profile that feels like you.' : 'Sign in to continue shaping your profile.'}</p>
    <form className="mt-8 space-y-5" onSubmit={submit} noValidate>{isRegister && <label className="block text-sm font-medium text-[#40594b]">Your name<input className="field mt-2" autoComplete="name" value={name} onChange={(e) => setName(e.target.value)} placeholder="e.g. Dr. Ananya Rao" required minLength={2} data-testid="input-name" /></label>}<label className="block text-sm font-medium text-[#40594b]">Email address<span className="relative mt-2 block"><Mail size={17} className="absolute left-4 top-1/2 -translate-y-1/2 text-[#8a978d]" /><input className="field pl-11" type="email" autoComplete="email" value={email} onChange={(e) => setEmail(e.target.value)} placeholder="you@example.com" required data-testid="input-email" /></span></label><label className="block text-sm font-medium text-[#40594b]">Password<input className="field mt-2" type="password" autoComplete={isRegister ? 'new-password' : 'current-password'} value={password} onChange={(e) => setPassword(e.target.value)} placeholder={isRegister ? 'At least 8 characters' : 'Your password'} required minLength={isRegister ? 8 : 1} data-testid="input-password" /></label>{problem && <div className="rounded-xl border border-[#e8c5b8] bg-[#fbebe5] px-4 py-3 text-sm text-[#9b5143]" role="alert" data-testid="status-auth-error">{problem}</div>}<button className="btn btn-primary w-full !py-3.5" type="submit" disabled={pending} data-testid="button-auth-submit">{pending ? <><LoaderCircle className="animate-spin" size={17} />{isRegister ? 'Creating your account…' : 'Signing you in…'}</> : <>{isRegister ? 'Create account' : 'Sign in'} <ArrowRight size={17} /></>}</button></form><p className="mt-7 text-center text-sm text-[#738076]">{isRegister ? 'Already have a profile?' : 'New to Unfazed?'} <Link href={isRegister ? '/login' : '/register'} className="font-semibold text-[#315b49] underline underline-offset-4" data-testid="link-switch-auth">{isRegister ? 'Log in' : 'Create an account'}</Link></p><div className="mt-8 flex items-center justify-center gap-2 text-xs text-[#899289]"><LockKeyhole size={13} />Secure sign-in, without storing your password here.</div></div><div className="pb-3 text-center text-[11px] text-[#9a9d92]">Unfazed · A space for your practice</div></section></main>;
}

function Dashboard() {
  const [, setLocation] = useLocation(); const client = useQueryClient();
  const { data: therapist, isLoading, isError, error, refetch } = useGetCurrentTherapist({ query: { queryKey: getGetCurrentTherapistQueryKey() } });
  const update = useUpdateTherapistProfile();
  const logout = useLogoutTherapist();
  const [name, setName] = useState(''); const [slug, setSlug] = useState(''); const [bio, setBio] = useState(''); const [specializations, setSpecializations] = useState(''); const [languages, setLanguages] = useState(''); const [serviceDrafts, setServiceDrafts] = useState<ServiceDraft[]>([]); const [saved, setSaved] = useState(false); const [copied, setCopied] = useState(false); const [problem, setProblem] = useState(''); const [initializedId, setInitializedId] = useState('');
  useEffect(() => { if (therapist && therapist.id !== initializedId) { setName(therapist.name); setSlug(therapist.slug); setBio(therapist.bio || ''); setSpecializations(therapist.specializations?.join(', ') || ''); setLanguages(therapist.languages?.join(', ') || ''); setServiceDrafts((therapist.services ?? []).map((service) => ({ title: service.title, description: service.description, durationMinutes: String(service.durationMinutes), feeInr: String(service.feeInr) }))); setInitializedId(therapist.id); } }, [therapist, initializedId]);
  const publicUrl = typeof window === 'undefined' ? `/${slug}` : `${window.location.origin}/${slug}`;
  const signOut = () => logout.mutate(undefined, { onSuccess: () => { client.removeQueries({ queryKey: getGetCurrentTherapistQueryKey() }); setLocation('/login'); }, onError: (err) => setProblem(errorMessage(err, 'We could not sign you out just now. Please try again.')) });
  const changeService = (index: number, key: keyof ServiceDraft, value: string) => setServiceDrafts((items) => items.map((item, itemIndex) => itemIndex === index ? { ...item, [key]: value } : item));
  const submit = (event: React.FormEvent<HTMLFormElement>) => {
    event.preventDefault(); setProblem(''); setSaved(false);
    const normalizedName = name.trim(); const normalizedSlug = makeSlug(slug);
    if (normalizedName.length < 2) { setProblem('Please enter a name with at least 2 characters.'); return; }
    if (normalizedSlug.length < 2) { setProblem('Your profile link needs at least 2 characters.'); return; }
    if (serviceDrafts.length > 12) { setProblem('You can add up to 12 session offerings.'); return; }
    const services: TherapistServiceInput[] = [];
    for (const [index, service] of serviceDrafts.entries()) {
      const title = service.title.trim(); const description = service.description.trim(); const feeInr = Number(service.feeInr);
      if (title.length < 2 || title.length > 100) { setProblem(`Offering ${index + 1}: enter a title between 2 and 100 characters.`); return; }
      if (description.length > 500) { setProblem(`Offering ${index + 1}: keep the description within 500 characters.`); return; }
      if (!['30', '45', '60', '90'].includes(service.durationMinutes)) { setProblem(`Offering ${index + 1}: choose a session duration.`); return; }
      if (service.feeInr.trim() === '' || !Number.isFinite(feeInr) || feeInr < 0) { setProblem(`Offering ${index + 1}: enter a valid fee in INR.`); return; }
      services.push({ title, description, durationMinutes: Number(service.durationMinutes) as TherapistServiceInput['durationMinutes'], feeInr });
    }
    const payload: TherapistProfileUpdate = { name: normalizedName, slug: normalizedSlug, bio: bio.trim(), specializations: splitTags(specializations), languages: splitTags(languages), services };
    update.mutate({ data: payload }, { onSuccess: (updated) => { client.setQueryData(getGetCurrentTherapistQueryKey(), updated); if (therapist?.slug) void client.invalidateQueries({ queryKey: getGetPublicTherapistProfileQueryKey(therapist.slug) }); void client.invalidateQueries({ queryKey: getGetPublicTherapistProfileQueryKey(updated.slug) }); setSlug(updated.slug); setName(updated.name); setBio(updated.bio || ''); setSpecializations(updated.specializations?.join(', ') || ''); setLanguages(updated.languages?.join(', ') || ''); setServiceDrafts((updated.services ?? []).map((service) => ({ title: service.title, description: service.description, durationMinutes: String(service.durationMinutes), feeInr: String(service.feeInr) }))); setSaved(true); }, onError: (err) => setProblem(errorMessage(err, 'Your changes could not be saved. Please try again.')) });
  };
  const copyLink = async () => { try { await navigator.clipboard.writeText(publicUrl); setCopied(true); window.setTimeout(() => setCopied(false), 2200); } catch { setProblem('Clipboard access is unavailable. You can select and copy the link above.'); } };
  if (isLoading) return <div className="min-h-[100dvh] bg-[#f3f0e7]"><Header dashboard /><div className="page-wrap py-14"><div className="h-8 w-56 animate-pulse rounded-lg bg-[#e4e4d9]" /><div className="mt-6 grid gap-6 md:grid-cols-[1.3fr_.7fr]"><div className="h-[560px] animate-pulse rounded-3xl bg-[#e8e6dc]" /><div className="h-72 animate-pulse rounded-3xl bg-[#e8e6dc]" /></div></div></div>;
  if (isError || !therapist) return <div className="min-h-[100dvh] bg-[#f3f0e7]"><Header dashboard /><div className="mx-auto max-w-lg px-6 py-24 text-center"><div className="mx-auto flex h-14 w-14 items-center justify-center rounded-full bg-[#f2e2d7] text-[#9b6551]"><LockKeyhole /></div><h1 className="serif mt-5 text-4xl text-[#294f43]">Your practice space awaits.</h1><p className="mt-3 text-[#718078]">{isError ? errorMessage(error, 'Please sign in to manage your profile.') : 'Please sign in to manage your profile.'}</p><div className="mt-7 flex justify-center gap-3"><button className="btn btn-ghost" onClick={() => void refetch()} data-testid="button-retry-session">Try again</button><Link href="/login" className="btn btn-primary" data-testid="link-dashboard-login">Log in</Link></div></div></div>;
  return <main className="min-h-[100dvh] bg-[#f3f0e7]"><Header dashboard onSignOut={signOut} signingOut={logout.isPending} /><div className="page-wrap py-9 md:py-14"><div className="flex flex-wrap items-end justify-between gap-5"><div><p className="eyebrow">Your practice, your space</p><h1 className="serif mt-2 text-5xl text-[#294f43]">Good morning, {therapist.name.split(' ')[0]}.</h1><p className="mt-3 text-[#738076]">Shape the first impression you want to leave.</p></div><div className="flex items-center gap-2 rounded-full border border-[#d6ddcf] bg-[#e8ede3] px-3 py-2 text-xs font-medium text-[#54715e]"><CheckCircle2 size={15} />Your profile is live</div></div>
    <div className="mt-9 grid items-start gap-6 lg:grid-cols-[1.2fr_.8fr]">
      <section className="surface rounded-[26px] p-6 sm:p-9">
        <div className="flex items-start justify-between gap-4 border-b border-[#e6e0d3] pb-6">
          <div><p className="eyebrow">Profile details</p><h2 className="serif mt-2 text-3xl text-[#315447]">Tell your story.</h2></div>
          <div className="flex h-12 w-12 shrink-0 items-center justify-center rounded-full bg-[#dfe7d8] text-sm font-semibold text-[#476453]" data-testid="text-profile-initials">{initials(therapist.name)}</div>
        </div>
        <form className="mt-6 space-y-5" onSubmit={submit} noValidate>
          <label className="block text-sm font-semibold text-[#40594b]">Name<input className="field mt-2" value={name} onChange={(e) => setName(e.target.value)} minLength={2} maxLength={100} data-testid="input-profile-name" /></label>
          <label className="block text-sm font-semibold text-[#40594b]">Your profile address<input className="field mt-2" value={slug} onChange={(e) => setSlug(makeSlug(e.target.value))} pattern="[a-z0-9]+(?:-[a-z0-9]+)*" minLength={2} maxLength={48} data-testid="input-profile-slug" /><span className="mt-1.5 block break-all text-xs font-normal text-[#8a938a]" data-testid="text-profile-origin">{publicUrl}</span><span className="mt-1.5 block text-xs font-normal text-[#8a938a]">Use lowercase letters, numbers and hyphens.</span></label>
          <label className="block text-sm font-semibold text-[#40594b]">A little about your practice<textarea className="field mt-2 min-h-[136px] resize-y leading-6" value={bio} onChange={(e) => setBio(e.target.value)} maxLength={3000} placeholder="Share the way you work, what matters to you, and what a first conversation might feel like." data-testid="input-profile-bio" /><span className="mt-1 block text-right text-xs font-normal text-[#8a938a]">{bio.length}/3000</span></label>
          <label className="block text-sm font-semibold text-[#40594b]">Areas you support<input className="field mt-2" value={specializations} onChange={(e) => setSpecializations(e.target.value)} placeholder="Anxiety, relationships, life transitions" data-testid="input-profile-specializations" /><span className="mt-1.5 block text-xs font-normal text-[#8a938a]">Separate each area with a comma.</span></label>
          <label className="block text-sm font-semibold text-[#40594b]">Languages you work in<input className="field mt-2" value={languages} onChange={(e) => setLanguages(e.target.value)} placeholder="English, Hindi, Marathi" data-testid="input-profile-languages" /></label>
          <section className="rounded-2xl border border-[#e6e0d3] bg-[#f8f6ef] p-4 sm:p-5">
            <div className="flex flex-wrap items-center justify-between gap-3"><div><p className="eyebrow">Session offerings</p><h3 className="serif mt-1 text-2xl text-[#315447]">Ways to work together</h3></div><button type="button" onClick={() => { if (serviceDrafts.length < 12) { setServiceDrafts((items) => [...items, blankService()]); setProblem(''); } }} disabled={serviceDrafts.length >= 12} className="btn btn-ghost !px-4 !py-2 text-sm" data-testid="button-add-service"><Plus size={16} />Add offering</button></div>
            <p className="mt-2 text-xs leading-5 text-[#818b81]">Add only the sessions you currently offer. You can list up to 12.</p>
            {serviceDrafts.length === 0 ? <div className="mt-4 rounded-xl border border-dashed border-[#d3d9cd] px-4 py-5 text-center text-sm text-[#7e897f]" data-testid="empty-services-dashboard">No session offerings added yet.</div> : <div className="mt-4 space-y-4">{serviceDrafts.map((service, index) => <article key={`service-${index}`} className="rounded-xl border border-[#e1dfd4] bg-[#fbfaf5] p-4" data-testid={`card-service-editor-${index}`}>
              <div className="mb-4 flex items-center justify-between"><span className="eyebrow">Offering {index + 1}</span><button type="button" onClick={() => setServiceDrafts((items) => items.filter((_, itemIndex) => itemIndex !== index))} className="inline-flex items-center gap-1 rounded-lg px-2 py-1 text-xs text-[#936456] hover:bg-[#f4e7df]" aria-label={`Remove offering ${index + 1}`} data-testid={`button-remove-service-${index}`}><Trash2 size={14} />Remove</button></div>
              <div className="space-y-3"><label className="block text-xs font-semibold text-[#52675a]">Session title<input className="field mt-1.5 !bg-[#f7f5ed] !py-2.5 text-sm" value={service.title} maxLength={100} onChange={(e) => changeService(index, 'title', e.target.value)} placeholder="e.g. Individual therapy" data-testid={`input-service-title-${index}`} /></label>
                <label className="block text-xs font-semibold text-[#52675a]">Description <span className="font-normal text-[#8a938a]">(optional)</span><textarea className="field mt-1.5 min-h-[76px] resize-y !bg-[#f7f5ed] !py-2.5 text-sm" value={service.description} maxLength={500} onChange={(e) => changeService(index, 'description', e.target.value)} placeholder="What someone can expect from this session." data-testid={`input-service-description-${index}`} /></label>
                <div className="grid gap-3 sm:grid-cols-2"><label className="block text-xs font-semibold text-[#52675a]">Duration<select className="field mt-1.5 !bg-[#f7f5ed] !py-2.5 text-sm" value={service.durationMinutes} onChange={(e) => changeService(index, 'durationMinutes', e.target.value)} data-testid={`select-service-duration-${index}`}><option value="">Choose duration</option><option value="30">30 minutes</option><option value="45">45 minutes</option><option value="60">60 minutes</option><option value="90">90 minutes</option></select></label><label className="block text-xs font-semibold text-[#52675a]">Fee in INR<input className="field mt-1.5 !bg-[#f7f5ed] !py-2.5 text-sm" type="number" min="0" step="0.01" inputMode="decimal" value={service.feeInr} onChange={(e) => changeService(index, 'feeInr', e.target.value)} placeholder="0" data-testid={`input-service-fee-${index}`} /></label></div>
              </div>
            </article>)}</div>}
          </section>
          {problem && <div className="rounded-xl border border-[#e8c5b8] bg-[#fbebe5] px-4 py-3 text-sm text-[#9b5143]" role="alert" data-testid="status-profile-error">{problem}</div>}
          {saved && <div className="flex items-center gap-2 text-sm text-[#4b7558]" role="status" data-testid="status-profile-saved"><CheckCircle2 size={16} />Your profile is up to date.</div>}
          <div className="flex flex-wrap items-center justify-between gap-3 border-t border-[#e6e0d3] pt-5"><p className="text-xs text-[#879087]">Your edits update your public profile.</p><button className="btn btn-primary" type="submit" disabled={update.isPending} data-testid="button-save-profile">{update.isPending ? <><LoaderCircle className="animate-spin" size={16} />Saving…</> : <>{saved ? 'Saved' : 'Save changes'}<Check size={16} /></>}</button></div>
        </form>
      </section>
    <aside className="space-y-5"><section className="relative overflow-hidden rounded-[26px] bg-[#365a4c] p-6 text-[#f6f2e8] sm:p-8"><div className="absolute -right-10 -top-14 h-48 w-48 rounded-full border border-white/10" /><div className="relative"><p className="eyebrow !text-[#c7d4b8]">A link to share</p><h2 className="serif mt-3 text-3xl">Your front door.</h2><p className="mt-2 text-sm leading-6 text-[#d2dcd2]">A simple way for someone to find you when they’re ready.</p><div className="mt-6 flex items-center gap-2 rounded-xl border border-white/15 bg-white/10 px-3 py-3"><span className="min-w-0 flex-1 truncate text-sm text-[#eff1e8]" data-testid="text-public-profile-url">{publicUrl}</span><button onClick={() => void copyLink()} aria-label="Copy profile link" className="flex h-9 w-9 shrink-0 items-center justify-center rounded-lg bg-white/10 hover:bg-white/20" data-testid="button-copy-profile-link">{copied ? <Check size={17} /> : <Clipboard size={17} />}</button></div><div className="mt-4 flex flex-wrap gap-3"><button onClick={() => void copyLink()} className="btn !bg-[#f0eee4] !text-[#365a4c] !px-4 !py-2.5 text-sm" data-testid="button-copy-link">{copied ? 'Copied' : 'Copy link'} <Clipboard size={15} /></button><a href={publicUrl} target="_blank" rel="noreferrer" className="btn !border !border-white/25 !text-white !px-4 !py-2.5 text-sm" data-testid="link-open-public-profile">Open profile <ExternalLink size={15} /></a></div></div></section><section className="rounded-[26px] border border-[#e1dbce] bg-[#ece9df] p-6"><div className="flex h-10 w-10 items-center justify-center rounded-full bg-[#dce4d5] text-[#476451]"><Heart size={18} /></div><h3 className="serif mt-4 text-2xl text-[#315447]">A thoughtful start</h3><p className="mt-2 text-sm leading-6 text-[#728076]">A clear profile can help someone feel a little more at ease reaching out. Keep it in your own words.</p></section></aside></div><div className="mt-7 flex items-center justify-center gap-2 text-xs text-[#8d9389]"><LockKeyhole size={13} />Your account is protected by a secure session.</div></div></main>;
}

function PublicProfile({ slug }: { slug: string }) {
  const { data: profile, isLoading, isError, error, refetch } = useGetPublicTherapistProfile(slug, { query: { queryKey: getGetPublicTherapistProfileQueryKey(slug) } });
  return <main className="min-h-[100dvh] bg-[#f3f0e7]">
    <header className="flex items-center justify-between border-b border-[#dfd9ca] px-5 py-4 md:px-10"><Brand /><span className="hidden text-xs tracking-wide text-[#7d897f] sm:block">A space for feeling understood</span></header>
    {isLoading ? <div className="page-wrap py-20"><div className="mx-auto h-16 w-16 animate-pulse rounded-full bg-[#dfe6d9]" /><div className="mx-auto mt-5 h-10 max-w-sm animate-pulse rounded bg-[#e5e2d7]" /><div className="mx-auto mt-4 h-24 max-w-xl animate-pulse rounded bg-[#e5e2d7]" /></div> : isError || !profile ? <div className="mx-auto max-w-lg px-6 py-24 text-center"><div className="mx-auto flex h-14 w-14 items-center justify-center rounded-full bg-[#e4eadf] text-[#4e725c]"><Sprout /></div><h1 className="serif mt-5 text-4xl text-[#294f43]">This page isn’t here yet.</h1><p className="mt-3 text-[#718078]">{errorMessage(error, 'We could not find this therapist profile. Check the address and try again.')}</p><div className="mt-7 flex justify-center gap-3"><button className="btn btn-ghost" onClick={() => void refetch()} data-testid="button-retry-public-profile">Try again</button><Link href="/" className="btn btn-primary" data-testid="link-public-home">Visit Unfazed</Link></div></div> : <>
      <section className="relative overflow-hidden bg-[#e8eadd] py-16 md:py-24"><div className="absolute -right-20 -top-24 h-[440px] w-[440px] rounded-full border border-[#d4dbcd]" /><div className="absolute -right-5 top-0 h-[330px] w-[330px] rounded-full border border-[#d4dbcd]" /><div className="page-wrap relative max-w-[850px] text-center"><div className="mx-auto flex h-[86px] w-[86px] items-center justify-center rounded-full border-[5px] border-[#f3f0e7] bg-[#c9d6c1] text-2xl font-semibold text-[#43604d] shadow-sm" data-testid="text-public-initials">{initials(profile.name)}</div><p className="eyebrow mt-6">Therapist · Private practice</p><h1 className="serif mt-3 text-6xl leading-none text-[#294f43] sm:text-7xl" data-testid="text-public-name">{profile.name}</h1><p className="serif mt-5 text-2xl italic text-[#a96f5b]">A space to find your footing.</p><p className="mx-auto mt-6 max-w-[620px] text-base leading-8 text-[#68766c]">{profile.bio || 'Every journey begins somewhere. This is a space to learn a little more about the support available.'}</p></div></section>
      <section className="page-wrap grid max-w-[900px] gap-7 py-12 md:grid-cols-[1fr_1fr] md:py-16">
        <article className="rounded-[26px] border border-[#e1dbce] bg-[#fbf9f2] p-7 sm:p-9"><p className="eyebrow">Areas of support</p><h2 className="serif mt-3 text-3xl text-[#315447]">What we can explore.</h2><div className="mt-6 flex flex-wrap gap-2">{profile.specializations?.length ? profile.specializations.map((item, index) => <span key={`${item}-${index}`} className="rounded-full border border-[#d7dfd1] bg-[#edf1e9] px-3.5 py-2 text-sm text-[#506b59]" data-testid={`tag-specialization-${index}`}>{item}</span>) : <p className="text-sm leading-6 text-[#778278]">Support shaped around what feels important to you.</p>}</div></article>
        <article className="rounded-[26px] border border-[#e1dbce] bg-[#e5eadf] p-7 sm:p-9"><p className="eyebrow">A conversation, in your language</p><h2 className="serif mt-3 text-3xl text-[#315447]">Languages spoken.</h2><div className="mt-6 flex flex-wrap gap-2">{profile.languages?.length ? profile.languages.map((item, index) => <span key={`${item}-${index}`} className="rounded-full bg-[#d3decf] px-3.5 py-2 text-sm text-[#48644f]" data-testid={`tag-language-${index}`}>{item}</span>) : <p className="text-sm leading-6 text-[#778278]">Language options will be shared during your first conversation.</p>}</div></article>
      </section>
      <section className="page-wrap max-w-[900px] pb-12" aria-labelledby="service-offerings-title">
        <div className="flex flex-wrap items-end justify-between gap-4"><div><p className="eyebrow">Ways to work together</p><h2 id="service-offerings-title" className="serif mt-2 text-4xl text-[#315447]">Session offerings.</h2></div><p className="text-sm text-[#7a877d]">Details to help you choose a first step.</p></div>
        {profile.services?.length ? <div className="mt-6 grid gap-4 sm:grid-cols-2">{profile.services.map((service, index) => <article key={service.id} className="rounded-[24px] border border-[#e1dbce] bg-[#fbf9f2] p-6 sm:p-7" data-testid={`card-public-service-${service.id || index}`}><div className="flex items-start justify-between gap-4"><div><h3 className="serif text-2xl text-[#315447]" data-testid={`text-service-title-${service.id || index}`}>{service.title}</h3>{service.description && <p className="mt-2 text-sm leading-6 text-[#738076]">{service.description}</p>}</div><span className="shrink-0 rounded-full bg-[#e4eadf] px-3 py-1.5 text-sm font-semibold text-[#45634f]" data-testid={`text-service-fee-${service.id || index}`}>{formatINR(service.feeInr)}</span></div><div className="mt-5 flex items-center gap-2 border-t border-[#e6e0d3] pt-4 text-sm text-[#718078]" data-testid={`text-service-duration-${service.id || index}`}><Clock3 size={15} />{service.durationMinutes} minutes</div></article>)}</div> : <div className="mt-6 rounded-[24px] border border-dashed border-[#d4dacc] bg-[#eceee5] px-6 py-10 text-center" data-testid="empty-public-services"><span className="mx-auto flex h-11 w-11 items-center justify-center rounded-full bg-[#dce4d5] text-[#4b6b56]"><IndianRupee size={19} /></span><h3 className="serif mt-4 text-2xl text-[#315447]">Session details coming into focus.</h3><p className="mx-auto mt-2 max-w-md text-sm leading-6 text-[#778278]">This therapist hasn’t added session offerings yet. You can still learn about their approach and areas of support above.</p></div>}
      </section>
      <section className="page-wrap max-w-[900px] pb-16"><div className="flex flex-col items-start justify-between gap-5 rounded-[26px] bg-[#365a4c] p-7 text-[#f6f2e8] sm:flex-row sm:items-center sm:p-9"><div><p className="eyebrow !text-[#c7d4b8]">When you feel ready</p><h2 className="serif mt-2 text-3xl">There’s no perfect way to begin.</h2><p className="mt-2 text-sm text-[#d2dcd2]">Take your time. Finding the right fit matters.</p></div><span className="flex h-12 w-12 shrink-0 items-center justify-center rounded-full bg-white/10"><ArrowRight /></span></div></section>
    </>}
    <footer className="border-t border-[#dfd9ca] py-6 text-center"><Link href="/" className="text-sm font-semibold tracking-tight text-[#426451]" data-testid="link-footer-brand">unfazed.</Link><p className="mt-1 text-[11px] text-[#8a9288]">A softer way to find support.</p></footer>
  </main>;
}
function SlugRoute() { const [, params] = useRoute('/:slug'); return <PublicProfile slug={params?.slug ?? ''} />; }
function Router() { return <RoutedErrorBoundary><Switch><Route path="/" component={Home} /><Route path="/register"><AuthPage mode="register" /></Route><Route path="/login"><AuthPage mode="login" /></Route><Route path="/dashboard" component={Dashboard} /><Route path="/:slug" component={SlugRoute} /><Route component={NotFound} /></Switch></RoutedErrorBoundary>; }
function RoutedErrorBoundary({ children }: { children: ReactNode }) { const [location] = useLocation(); return <ErrorBoundary resetKey={location}>{children}</ErrorBoundary>; }
function App() { return <QueryClientProvider client={queryClient}><TooltipProvider><WouterRouter base={import.meta.env.BASE_URL.replace(/\/$/, '')}><Router /></WouterRouter><Toaster /></TooltipProvider></QueryClientProvider>; }
export default App;
